channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.11.7

  - pip=23.0.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==22.5.3 # https://rpaframework.org/releasenotes.html
      - psycopg2==2.9.9
      #- sshtunnel==0.4.0
      - nepali-datetime==1.0.8.1
      - pandas==2.2.0
      #- prettytable==3.9.0
